### ISSUE TITLE
Move keyboard to the side if screen rotates to horizontal

### ISSUE THREAD

**Issue by AndiZ23** [Andrew67/ddr-calc#22]

**Comment by Andrew67** [comment]
PWA meta-data requests portrait orientation lock but iOS ignores this.
Low priority.

**Comment by Andrew67** [comment]
Google Chrome in TWA mode also ignores the orientation lock request.
Priority is slightly higher.

**Comment by Andrew67** [comment]
Closing as wont-fix. TWA respects orientation lock + one-handed-mode keyboard can appear when the screen is not tall enough for the full keyboard.
